### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [IlyaShein/Fortran-reducer#1]
I suggest adding the topics `fortran`, `build-tool` in the About section of https://github.com/IlyaShein/Fortran-reducer .

**Comment by IlyaShein** [comment]
Thank you, that's a good point. Build-tool has been added. Can I close an issue?

**Comment by IlyaShein** [comment]
> I suggest adding the topics `fortran`, `build-tool` in the About section of https://github.com/IlyaShein/Fortran-reducer .

Thank you, that's a good point. Build-tool has been added. Can I close an issue?

**Comment by Beliavsky** [comment]
`build-tool` should appear in the About section as it does for https://github.com/gradle/gradle for example. How to add a topic is described at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics .

**Comment by IlyaShein** [comment]
> `build-tool` should appear in the About section as it does for https://github.com/gradle/gradle for example. How to add a topic is described at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics .

Thanks, I think the build-tool doesn't look so bad and I'll leave it like this. Can you tell me what the Fortran topic means?

**Comment by Beliavsky** [comment]
A tag such as `fortran` just means that the repo is about Fortran in some way.

**Comment by IlyaShein** [comment]
> A tag such as `fortran` just means that the repo is about Fortran in some way.

Thanks, I'm added tag fortran
